name: Terraform Validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform -chdir=iac init -backend=false

      - name: Terraform Format Check
        run: terraform -chdir=iac fmt -check -recursive

      - name: Terraform Validate
        run: terraform -chdir=iac validate
